version: '3.9'

services:
  onlineBlog_app:
    container_name: onlineBlog_app
    image: onlineblog_app:1.0.0
    build: .
    restart: always
    ports:
      - '8000:8080'
    environment:
      - DATABASE_URL=
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
    depends_on:
      -

  mysql_db:
    container_name: mysql_db
    image: mysql:8.2.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    volumes:

networks:


volumes:
