services:
  onlineBlog_app:
    container_name: onlineBlog_app
    image: onlineblog_app:1.0.0
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=jdbc:mysql://mysql_db:3306/onlineblog
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
    networks:
      - 'onlineblog-network'
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:8.2.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=onlineblog
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - 'onlineblog-network'

networks:
  onlineblog-network:

volumes:
  mysql-data:
